---
- name: "Check for syslogng_exporter binary"
  ansible.builtin.stat:
    path: "/usr/local/bin/syslogng-exporter"
  changed_when: false
  register: syslogng_exporter_install

- name: "Install tasks"
  when: not syslogng_exporter_install.stat.exists
  block:
    - name: "Install requierements"
      ansible.builtin.package:
        name: "ca-certificates"
        state: present
      register: pkg_result
      retries: 12
      delay: 10
      until: pkg_result is success

    - name: "Download syslogng_exporter..."
      ansible.builtin.get_url:
        url: '{{ syslogng_exporter_url }}'
        dest: /usr/local/bin/syslogng-exporter
        timeout: 120
        mode: '0755'

- name: "Create symtemd for syslogng_exporter"
  ansible.builtin.template:
    src: "syslogng_exporter.service.j2"
    dest: "/lib/systemd/system/syslogng_exporter.service"
    mode: '0644'
  notify: "Restart syslogng_exporter"

- name: "Start syslogng_exporter.service"
  ansible.builtin.service:
    name: syslogng_exporter
    state: started
    enabled: true
    daemon_reload: true
