---
- name: Check for syslogng_exporter binary
  stat:
    path: "/usr/local/bin/syslogng-exporter"
  changed_when: false
  register: syslogng_exporter_install

- when: not syslogng_exporter_install.stat.exists
  block:
    - name: "Install requierements"
      package:
        name: "ca-certificates"
        state: present

    - name: download syslogng_exporter...
      get_url:
        url: '{{ syslogng_exporter_url }}'
        dest: /usr/local/bin/syslogng-exporter
        timeout: 120
        mode: 0755

- name: Create symtemd for syslogng_exporter
  template:
    src: "syslogng_exporter.service.j2"
    dest: "/lib/systemd/system/syslogng_exporter.service"
    mode: 0644
  notify: "restart syslogng_exporter"

- name: Start syslogng_exporter.service
  service:
    name: syslogng_exporter
    state: started
    enabled: true
    daemon_reload: true
